@startuml
'https://plantuml.com/state-diagram

scale 1000 width
[*] -left-> u  : arch != RaspberryPi
[*] -down-> r : arch == RaspberryPi

state "Running" as r {
r: on: post(undefined) / BAD_REQUEST
r: on: tick -> broadcast(heartbeat);\n\t\t checkSuspendTimeTable();\n\t\t updateTimeTableUi()
r: on: post(timetabelChanged):\n\t\t checkSuspendTimeTable();\n\t\t updateTimeTableUi()
[*] -down-> no

state "NormalOperation" as no
    no: entry: post(normal)

state "Suspended" as sup
    sup: entry: post(suspend)
}

state "Undefined" as u

no -down-> sup : suspend
sup -up-> no : resume

u -down-> [*]

@enduml