@startuml
scale 900 width
'https://plantuml.com/class-diagram
package de.geobe.energy {
    package acquire {
        class PvMonitor <<actor>><<singleton>>{}
        class Reading <<datatype>>{}
        class S10Access{}
        class SinglePage{}
    }
}

package de.geobe.energy.heatpump{
    class HeatpumpManager <<actor>><<singleton>>{}
    class HeatpumpController <<bridge>>
}

@enduml